# Implementation derived from `.cirrus.yml` in Rust's libc bindings
# at revision 7f4774e76bd5cb9ccb7140d71ef9be9c16009cdf.

task:
  name: stable x86_64-unknown-freebsd-14
  freebsd_instance:
    image_family: freebsd-14-2
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain stable -y --profile=minimal
    - . $HOME/.cargo/env
    - rustup default stable
  test_script:
    - . $HOME/.cargo/env
    - cargo test --workspace --features=all-apis

task:
  name: stable x86_64-unknown-freebsd-15
  freebsd_instance:
    image_family: freebsd-15-0-snap
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain stable -y --profile=minimal
    - . $HOME/.cargo/env
    - rustup default stable
  test_script:
    - . $HOME/.cargo/env
    - cargo test --workspace --features=all-apis
